{
  "language": "ruby",
  "rvm": 2.2,
  "before_script": [
    "gem install awesome_bot"
  ],
  "script": [
    "awesome_bot README.md --allow-dupe --allow-redirect --white-list creativecommons,travis-ci.org,github.com/EpicGames/,github.com/NvPhysX/"
  ],
  "group": "stable",
  "os": "linux"
}
